---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  changed_when: false
- name: Ensure InfluxDB is installed.
  apt:
    name: influxdb
    state: installed
- name: Copy InfluxDB configuration
  template: src=influxdb.conf dest=/etc/influxdb/influxdb.conf
  notify: restart influxdb
